### ISSUE TITLE
Key polling

### ISSUE THREAD

**Issue by jggames** [gregdionne/mcbasic#2]
Hey Greg,  Been working with Loderunner to make it work as a compiled BASIC program.  Got my workflow down to a smooth routine.  Compiler seems good.  Only issue, and this might be MC-10 related rather than the compiler, remains the occasional key latching.  Sometimes the key you press doesn't switch to that direction and you just keep going in the prior direction.  You have to let up and press another key, and then you can press the key you want to get going.  If there was any way around this or a smooth over of some sort, I've got pretty long delay loop so I can do lots of extra stuff (peeks? pokes?) if those might help.  Or are there possibly some key combinations that might avoid the problem somehow?  I'm using WASD and , and .

Thanks again for all the work.  I'm looking forward to converting a number of my programs that I think would really benefit from compilation.  I've got a bunch, which I might need to get rid of VARPTR references and using other more standard techniques liie MID$ to accomplish the same task.

**Comment by gregdionne** [comment]
Hi Jim,

I’ve noticed the keyboard issue as well with my setup.  This seems to happen even without the compiler.  For example, if I enter in LODERUN32.TXT I will often find I cannot move right by pressing “S” without pressing some other key first.  It’s not always reproducible though. 

I think perhaps for something more reliable that should work in BASIC you can try this instead of PEEK(2) AND PEEK(17023):

PEEK(2) AND _MASK_ AND NOT PEEK(_KEYGROUP_) using the keygroup and mask shown below:

KEYGROUP| 1 | 2 | 4 |  8  | 16 | 32
--------|---|---|---|-----|----|-----
 16945  | @ | H | P |  X  | 0  |  8
 16946  | A | I | Q |  Y  | 1  |  9
 16947  | B | J | R |  Z  | 2  | : *
 16948  | C | K | S |     | 3  | ; +
 16949  | D | L | T |     | 4  | , <
 16950  | E | M | U |     | 5  | - =
 16951  | F | N | V | ENT | 6  | . >
 16952  | G | O | W | SPC | 7  | / ?

This should work most of the time even when more than one key is down.  Here is sample code to get you started.

5 CLS
10 ?@1,"w";
20 IF PEEK(2) AND 4 AND NOT PEEK(16952) THEN PRINT@1,"W";
30 ?@2,"a";
40 IF PEEK(2) AND 1 AND NOT PEEK(16946) THEN PRINT@2,"A";
50 ?@3,"s";
60 IF PEEK(2) AND 4 AND NOT PEEK(16948) THEN PRINT@3,"S";
70 ?@4,"d";
80 IF PEEK(2) AND 1 AND NOT PEEK(16949) THEN PRINT@4,"D";
90 ?@5,",";
100 IF PEEK(2) AND 32 AND NOT PEEK(16949) THEN PRINT@5,"<";
110 ?@6,".";
120 IF PEEK(2) AND 32 AND NOT PEEK(16951) THEN PRINT@6,">";
130 GOTO 10 


Try pressing multiple keys at once to get a sense of its limitations.  

If this interests you, I can tweak the compiler to support it.  

Best,
-Greg

**Comment by jggames** [comment]
So the compiler doesn't support these commands right now?  But you think it would provide more reliable key polling?  I'd definitely be interested in implementing it in the compiler if you thought this method would avoid some of the key latching issue.  There's plenty of room for such more complicated processing with the speed you have provided.  My problem now is slowing things down appropriately.

**Comment by gregdionne** [comment]
I've added support for the keystrobe buffer.   That lets you keep the same source code for both compiled and interpreted execution.  

Have a look at tests/testkeystrobe.bas.
