### ISSUE TITLE
":" expected

### ISSUE THREAD

**Issue by jggames** [gregdionne/mcbasic#4]
I'm getting this message when I try to compile my SWELFOOP

":" expected

Here's the file:
[(https://github.com/jggames/trs80mc10/blob/master/quicktype/Puzzle/SwelFoop/SWELFOOPcompiler8.TXT]
I've gone though it looking for anomalous code, but can't find anything obvious.

**Comment by gregdionne** [comment]
The compiler doesn't yet parse the "^" operator.  

    > mcbasic swelfoop.bas
    Compiling swelfoop.bas...
    swelfoop.bas(75): 2200 SC=SC+(YD-2)^2:GOTO1700
                                       ^
    ":" expected

I hadn't added EXP and LOG until this morning, so I suppose that explains that "^" doesn't quite work yet.  I'll tweak it so that a parse error properly emits the offending line, and add an optimization when it sees an integer exponent.

A workaround is to simply do:  (YD-2)*(YD-2)

**Comment by gregdionne** [comment]
I've added support for the ^ operator, compiled and run swelfoop.  
It's added to the examples directory now.

**Comment by jggames** [comment]
Hadn't noticed that ^ wasn't supported.  Thanks for getting adding that!
