### ISSUE TITLE
F=-(F=0) returns -65535 when false

### ISSUE THREAD

**Issue by jggames** [gregdionne/mcbasic#6]
Greg,

I noticed that the following command, which is just supposed to creation an oscillating value between 0 and 1 actually returns -65535 when it should return a 0:

F=-(F=0)

In other words, F is initialized to 0 at program startup, passes through the command and is switched to a 1.  Then in the second round of the game, a one is passed to it, and it should return a 0 (false) which is negated but should remain a 0.  But instead of false -(0) -65535 is returned.

Replaced it with the following and things worked fine:
700 IFF=0THENF=1:GOTO720
710 IFF=1THENF=0
720 RETURN

Jim

**Comment by gregdionne** [comment]
Thank you for narrowing it down, Jim!  

I tried reproducing it with the JavaScript emulator, but alas, it seems to be working ok:
```
10 F=0
15 PRINT F
20 F=-(F=0)
25 PRINT F
30 F=-(F=0)
35 PRINT F
40 F=-(F=0)
45 PRINT F
50 F=-(F=0)
55 PRINT F
```
![image](https://user-images.githubusercontent.com/29028499/108447910-be32e280-722e-11eb-8cfd-13d877c82a31.png)

Let me know if this code works for you as well (to rule out an emulator issue).
Otherwise I'll have to get a copy of your program and try it out this weekend.  

Best
-Greg

**Comment by jggames** [comment]
Greg,

Strange.  I thought I had tracked it down pretty solidly, but perhaps it was not from the command but some weirdness with the assignment prior to getting to it.  Anyway, good to hear.  I’ll look into it over the weekend and see if I can find out more. In any case, ALPHAFOR is running okay now. 

Jim

Sent from Mail for Windows 10

**Comment by gregdionne** [comment]
Hi Jim!  

I've tracked down what a likely culprit would be and it could be our beloved negate-with-carry instruction.  I use the negate with carry in a few places (negation, signed multiplication/division, DATA/INPUT read of a negative number, trig functions) so it's important to get "right."  While we've verified (more than a decade ago) in the old Yahoo group that the instruction does indeed perform negate-with-carry, I don't remember us ever verifying that it sets the carry flag in the way I've been using it.  It could instead be the "add complement, one, and carry" (ACOC), in which case the output carry would be set in the opposing sense.    (see the first "CALM" instruction here:  https://old.didel.com/picg/docfaeh/CALMINS-E.TXT ).  Since I daisy-chain them together like:
```
  neg 2,x  ; negate lower byte
  ngc 1,x  ; negate middle byte
  ngc 0,x  ; negate upper byte
```
The low-order bytes will be set correctly, but if the _output_ carry of the instruction is like ACOC instead of a NEGC, then the upper byte won't get negated correctly.  So, if asked to operate over a series of zeros, then it would complement the upper byte (zero) to 255 ($FF), but fail to add the carry (that would restore it to zero).  The resulting 24-bit two's complement value would be -65536  ($FF, $00, $00).  I'm not sure why you would get -65535 ($FF, $00, $01) but maybe it happened after a a return of -1.  (If -1 were to be incorrectly negated you could get $FF, $00, $01 for similar reasons).  It does what I think it should do in the JavaScript emulator... but maybe it's doing the opposite in the Virtual MC-10.

So please do try out the test code on a _real_ MC-10.  That is, of course, the gold reference.

**Comment by gregdionne** [comment]
Another thing to try would be a simple negation:

10 X = -1
20 PRINT X; -X
30 X = 0;
40 PRINT X; -X

I don't do constant propagation (yet) so it shouldn't try to optimize out.

**Comment by jggames** [comment]
Dear Greg,

I’ll try recompiling my wonky version of ALPHAFOR and running it on real hardware shortly (I’ve had some marking I’ve been dealing with).  Will let you know what happens.  Probably Feb 23 evening (Tomorrow).

On another note.  I’ve been in contact with L. Curtis Boil from over on the Coco side of things.  He wants to have you on the Cocotalk show to talk about your compiler (and Pacman too I think).  He asked me if I had your email.  I told him I only have your contact through Github (at least that I can find).  Do you have an email you might be willing to share with him?

Sincerely,
Jim

Sent from Mail for Windows 10

**Comment by jggames** [comment]
Dear Greg,

I tried my wonky version of ALPHAFOR on real hardware and it ran fine.  Same (obviously) for Mike’s Javascript emulator.  But it throws the same error in James' emulator (Version I).

Tried the following compiled in James’ emulator:

10 X = -1
20 PRINT X; -X
25 Y=-(X=0):PRINTY
30 X = 0
40 PRINT X; -X
45 Y=-(X=0):PRINTY

Here’s what came out:
 
![test](https://user-images.githubusercontent.com/8966298/108893753-d4062600-75e7-11eb-8264-c4ecae011a13.png)

Looks like a problem for James.  Looks llike I'll have to switch to using Javascript EMU.
Jim

**Comment by jggames** [comment]
Real MC-10 runs it fine with:
-1    1
 0  
 0    0
 1
as output. 

The output is really weird on VMC10.  After the assignment of -1 to X, the value printed for X is -0! What's up with that?  The problem is not in the logical comparison at line 25 like I thought but in the printing of X in line 20 after a simple variable assignment!

**Comment by gregdionne** [comment]
Thank you, again, for narrowing this down.

I suppose I can reach out to James and let him know.  He may have implemented the output carry as consistent with "[complement data] + [not carry]" instead of "0 - (data + carry)".   

I do make use of the NGC instructions when converting numeric values to a string format.  I negate it as a two's complement fixed point value (24-bit signed integer, 16-bit fraction), so a -1 is stored internally as $FF, $FF, $FF, $00, $00.  I do a proper negate on the last $00 which sets the carry correctly, but then do an NGC on the preceding bytes from "right to left", the first NGC on the $00 gets the proper carry out, so it remains a $00, but if it doesn't set its output carry, then the $FF would only be complemented to $00 (not set to $01).  

It is such a compact and handy instruction.  It is a shame Motorola didn't document it for either the 6801 or 6809, especially since neither cpu has a NEGD instruction.

**Comment by gregdionne** [comment]
I've made the NGC instructions available by using an "-undoc" flag.  If you don't specify it, it will just use the "official" opcodes by the 6801.  That way your code will work with non-compliant emulators.
